### ISSUE TITLE
Cannot clone and build with IntelliJ IDEA

### ISSUE THREAD

**Issue by gordonaspin** [carter-ya/idea-plugin-jpa-support#101]
repo is not complete. Cannot build locally. Please provide instructions.

**Comment by carter-ya** [comment]
1. Use IDEA to clone the project
2. Use gradle to execute task: `eg runide`
![image](https://user-images.githubusercontent.com/18641671/114294215-9db93300-9acf-11eb-9bff-88017e203488.png)

**Comment by gordonaspin** [comment]
Thank you for your response


12:32:50 PM: Executing task 'runide'...

> Configure project :
use remote version: 2020.3.2
> Task :generateLombokConfig

> Task :compileJavaidea-plugin-jpa-support2/src/main/java/com/ifengxue/plugin/action/JpaSupportWithDatabasePlugin.java:15: error: package com.intellij.database.model does not exist
import com.intellij.database.model.DasNamespace;
                                  ^

I had to add to build.gradle
dependencies {
    compileOnly fileTree('/Applications/IntelliJ IDEA.app/Contents/plugins/DatabaseTools/lib')
}

Is this the correct approach ?

**Comment by carter-ya** [comment]
Sorry, I have now added `database-openapi.jar` to VCS, you can now update the project and re-execute`runide`

**Comment by gordonaspin** [comment]
Great!

I would like to see:
1. Service implementation generated
2. Run generation as a build step without need to use plugin UI
3. Configurable use of @EmbeddedId for composite PK and separate Serializable classes for those PKs
4. Generation of Test Cases for all entities/repositories that do findOne and/or findAll
5. Migrate to maven build ?
6. IBM DB2 and Oracle jdbc 

Great work!

**Comment by gordonaspin** [comment]
Maybe consider migrating away from Apache velocity template to use StringTemplate / ST4 ? Much more flexible.

**Comment by carter-ya** [comment]
> Migrate to maven build ?
You can't, because IDEA Plugin not support use maven.
> Use ST4?
The acceptance of using velocity will be higher, and many configurations of IDEA can also use velocity, such as `Copyright`
> DB2,Oracle?
Also support DB2,Oracle. You can use Database Plugin Or specify JDBC driver.
