### ISSUE TITLE
自动生成选项：移除前缀只能否支持匹配多个前缀

### ISSUE THREAD

**Issue by pdkst** [carter-ya/idea-plugin-jpa-support#104]
- 一个是自动生成选项能否支持移除多个前缀：`a_,b_,c_`同时移除`a_`、`b_`、`c_`
- 另外一个是`Tools`-`JAP Support`能否加一些特殊规则，比如以id结尾的字段（正则：`[iI]d$`），使用`Long`类型（数据库类型是`int`）

**Comment by carter-ya** [comment]
> 一个是自动生成选项能否支持移除多个前缀：a_,b_,c_同时移除a_、b_、c_

下个版本支持

> 另外一个是Tools-JAP Support能否加一些特殊规则，比如以id结尾的字段（正则：[iI]d$），使用Long类型（数据库类型是int）

需要调研

**Comment by pdkst** [comment]
补充说明：
![image](https://user-images.githubusercontent.com/8915631/115982266-500ef100-a5cc-11eb-8bcb-f28ef00bedc5.png)
第二个是在红框位置（或最后位置）加一个特殊选项，替换最后映射的类型

**Comment by carter-ya** [comment]
> 另外一个是Tools-JAP Support能否加一些特殊规则，比如以id结尾的字段（正则：[iI]d$），使用Long类型（数据库类型是int）

数据库类型为int，代码中是long，有点不合理

**Comment by pdkst** [comment]
> > 另外一个是Tools-JAP Support能否加一些特殊规则，比如以id结尾的字段（正则：[iI]d$），使用Long类型（数据库类型是int）
> 
> 数据库类型为int，代码中是long，有点不合理

这个我可以解释，MySQL单表存储一千万条记录后索引层级就会变高导致性能不好，实际上从0开始数据不会超过int的表示范围，一般都是用int类型节省存储，一般是int(11)最高到十亿，但是实体规范的话一般是推荐Long类型的，目前都是生成后用正则替换，所以想着有没有选项从源头解决😂
