### ISSUE TITLE
Unable to select database 'views' on 'Generate JPA Entities' dialog box

### ISSUE THREAD

**Issue by riteshka** [carter-ya/idea-plugin-jpa-support#109]
In a previous version, the 'Generate JPA Entities' dialog allowed selecting views. But with the latest version, only tables are listed in the dialog. Can the support for views be added back?

**Comment by carter-ya** [comment]
![image](https://user-images.githubusercontent.com/18641671/117385284-5f206800-af17-11eb-96f4-7ed7d8955808.png)


[https://plugins.jetbrains.com/plugin/10707-jpa-support/reviews#review=53363](https://plugins.jetbrains.com/plugin/10707-jpa-support/reviews#review=53363)

**Comment by riteshka** [comment]
I have tried several drivers but none seem to work. 

My backend database is Oracle 12c.
Would you be able to provide a driver version that works for this version of the DB? Also, nothing has changed from my side and it used to work until I updated to the latest version of this plugin. So, I am not sure if its just a driver issue, something has changed in the plugin as well. It would be nice and very helpful if you could provide more insight into this then just asking for updating the driver version.

**Comment by carter-ya** [comment]
I cannot find Oracle 12c for testing. Can you provide a test instance?

**Comment by riteshka** [comment]
You can use this link to download 18c or 11g versions. The issue is same for all these versions

https://www.oracle.com/database/technologies/xe-downloads.html

Once again, a previous version of the plugin works correctly but not the latest. So, I would first look at if something changed within the plugin. But feel free to test and please let me know if you need any further information.

Thanks for all your help. The plugin works great otherwise.

**Comment by riteshka** [comment]
I reverted back the plugin to use 2.0.6.EAP version and it works as expected. I am able to select the views for creating entities. Same driver, same database. This tells me that new version has some changes that are making it incompatible with views.

**Comment by carter-ya** [comment]
Thanks for your feedback, I will fix the problem! I have been busy recently, and the repair time may be uncertain.

**Comment by riteshka** [comment]
No worries. Thanks for looking into this.

**Comment by carter-ya** [comment]
![1](https://user-images.githubusercontent.com/18641671/121033724-03c7eb00-c7df-11eb-9927-fcecc42cde5e.png)
![2](https://user-images.githubusercontent.com/18641671/121033734-0591ae80-c7df-11eb-84ae-f1134f771cbd.png)

I installed oracle on my own computer, and created a view, `JPA Support` can correctly identify.

**Comment by riteshka** [comment]
Thanks. I will test it. Just curious, did you had to fix the code to make it work or it worked without any code changes.

**Comment by carter-ya** [comment]
> Thanks. I will test it. Just curious, did you had to fix the code to make it work or it worked without any code changes.

Did not reproduce the problem you mentioned, so no repairs will be made.

But, I upgraded the plugin to support selecting View and Mat view through Database Tools.

**Comment by riteshka** [comment]
Ok. Thanks again. The latest version of plugin still doesn't display list of views. I have reverted back to using 2.0.6.EAP which works fine. I am going to close this issue as unresolved. Thanks for looking into it.
