### ISSUE TITLE
[BUG] Unable to create connection to Oracle Database

### ISSUE THREAD

**Issue by harikesh409** [carter-ya/idea-plugin-jpa-support#117]
**Describe the bug （描述这个Bug）**
As soon as I click on next in database connection creation the IntelliJ is getting hanged.

**Expected behavior （期望的行为）**
Connection Should be created and moved to the next step.

**Screenshots （截图，如果有的话）**
![image](https://user-images.githubusercontent.com/3501554/123130532-73d6a200-d46a-11eb-9fce-9f6c2fd1008c.png)

**idea version (idea的版本号):**
IntelliJ IDEA 2021.1.2 (Community Edition)

**idea plugin jpa support version (idea plugin jpa support的版本号）:**
2.0.7

[threadDump-20210623-212156.txt](https://github.com/carter-ya/idea-plugin-jpa-support/files/6703310/threadDump-20210623-212156.txt)

**Comment by carter-ya** [comment]
Please fill in this URL format?
https://github.com/carter-ya/idea-plugin-jpa-support/issues/109#issuecomment-855976396

**Comment by harikesh409** [comment]
> Please fill in this URL format?
> [#109 (comment)](https://github.com/carter-ya/idea-plugin-jpa-support/issues/109#issuecomment-855976396)

That's the same format we are using. Here is the screenshot will full details.
![image](https://user-images.githubusercontent.com/3501554/123380764-7988d080-d5ad-11eb-9c94-b9514e079a30.png)

**Comment by carter-ya** [comment]
Is there an error message when you click the'Next' button?

If there is no error message, you need to wait for a while, it may be because you have a large number of tables.

**Comment by harikesh409** [comment]
> Is there an error message when you click the'Next' button?
> 
> If there is no error message, you need to wait for a while, it may be because you have a large number of tables.

There is no error message on click of the Next button just the application gets hanged, I have waited for 10mins and if I check the IDE logs I am seeing freeze errors. Attached the threadDump in the issue itself.

**Comment by carter-ya** [comment]
> > Is there an error message when you click the'Next' button?
> > If there is no error message, you need to wait for a while, it may be because you have a large number of tables.
> 
> There is no error message on click of the Next button just the application gets hanged, I have waited for 10mins and if I check the IDE logs I am seeing freeze errors. Attached the threadDump in the issue itself.

Does the earlier version of the plugin work properly, eg: 2.0.6?

**Comment by carter-ya** [comment]
The plugin is trying to load the driver:
```plain
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE

	at java.base@11.0.11/java.lang.ClassLoader.findBootstrapClass(Native Method)
	at java.base@11.0.11/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1258)
	at java.base@11.0.11/java.lang.System$2.findBootstrapClassOrNull(System.java:2134)
	at java.base@11.0.11/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:118)
	at java.base@11.0.11/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:616)
	at java.base@11.0.11/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base@11.0.11/java.lang.ClassLoader.loadClass(ClassLoader.java:576)
	at java.base@11.0.11/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base@11.0.11/java.lang.Class.forName0(Native Method)
	at java.base@11.0.11/java.lang.Class.forName(Class.java:398)
	at org.mybatis.generator.internal.ObjectFactory.internalClassForName(ObjectFactory.java:144)
	at org.mybatis.generator.internal.ObjectFactory.createInternalObject(ObjectFactory.java:180)
	at org.mybatis.generator.internal.ObjectFactory.createIntrospectedColumn(ObjectFactory.java:360)
	at org.mybatis.generator.internal.db.DatabaseIntrospector.getColumns(DatabaseIntrospector.java:522)
	at org.mybatis.generator.internal.db.DatabaseIntrospector.introspectTables(DatabaseIntrospector.java:176)
	at com.ifengxue.plugin.gui.DatabaseSettingsDialog.findDatabaseSchemas(DatabaseSettingsDialog.java:266)
	at com.ifengxue.plugin.gui.DatabaseSettingsDialog.lambda$doOKAction$7(DatabaseSettingsDialog.java:221)
	at com.ifengxue.plugin.gui.DatabaseSettingsDialog$$Lambda$4545/0x0000000102856840.run(Unknown Source)
```

Can you change a driver version?

**Comment by harikesh409** [comment]
> The plugin is trying to load the driver:
> 
> ```
> "AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 runnable
>      java.lang.Thread.State: RUNNABLE
> 
> 	at java.base@11.0.11/java.lang.ClassLoader.findBootstrapClass(Native Method)
> 	at java.base@11.0.11/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1258)
> 	at java.base@11.0.11/java.lang.System$2.findBootstrapClassOrNull(System.java:2134)
> 	at java.base@11.0.11/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:118)
> 	at java.base@11.0.11/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:616)
> 	at java.base@11.0.11/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
> 	at java.base@11.0.11/java.lang.ClassLoader.loadClass(ClassLoader.java:576)
> 	at java.base@11.0.11/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
> 	at java.base@11.0.11/java.lang.Class.forName0(Native Method)
> 	at java.base@11.0.11/java.lang.Class.forName(Class.java:398)
> 	at org.mybatis.generator.internal.ObjectFactory.internalClassForName(ObjectFactory.java:144)
> 	at org.mybatis.generator.internal.ObjectFactory.createInternalObject(ObjectFactory.java:180)
> 	at org.mybatis.generator.internal.ObjectFactory.createIntrospectedColumn(ObjectFactory.java:360)
> 	at org.mybatis.generator.internal.db.DatabaseIntrospector.getColumns(DatabaseIntrospector.java:522)
> 	at org.mybatis.generator.internal.db.DatabaseIntrospector.introspectTables(DatabaseIntrospector.java:176)
> 	at com.ifengxue.plugin.gui.DatabaseSettingsDialog.findDatabaseSchemas(DatabaseSettingsDialog.java:266)
> 	at com.ifengxue.plugin.gui.DatabaseSettingsDialog.lambda$doOKAction$7(DatabaseSettingsDialog.java:221)
> 	at com.ifengxue.plugin.gui.DatabaseSettingsDialog$$Lambda$4545/0x0000000102856840.run(Unknown Source)
> ```
> 
> Can you change a driver version?
I have tried with 19, 20, and 21versions can you suggest some other version to try? Also, can you tell me how much time to wait should I wait more than 5minutes?

**Comment by carter-ya** [comment]
I don’t think this is a plugin problem, maybe you can try to upgrade the version of IDEA.

You also can try search in Google: `java.lang.ClassLoader.findBootstrapClass blocked`

**Comment by harikesh409** [comment]
> I don’t think this is a plugin problem, maybe you can try to upgrade the version of IDEA.
> 
> You also can try search in Google: `java.lang.ClassLoader.findBootstrapClass blocked`

Using the latest version of IDEA only, maybe the plugin is unable to handle huge data. Is there any kind of pagination or lazy loading implemented while pulling the database metadata?

**Comment by carter-ya** [comment]
> > I don’t think this is a plugin problem, maybe you can try to upgrade the version of IDEA.
> > You also can try search in Google: `java.lang.ClassLoader.findBootstrapClass blocked`
> 
> Using the latest version of IDEA only, maybe the plugin is unable to handle huge data. Is there any kind of pagination or lazy loading implemented while pulling the database metadata?

This is not a small workload, it may take a long time to develop... you can try to use IDEA Ultimate, the plugin supports to generate code through the Database Tool

**Comment by harikesh409** [comment]
Okay, I will try with the Ultimate edition.
