### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by xiamaoxuan** [carter-ya/idea-plugin-jpa-support#120]
1.建议增加一个是否逻辑删除的功能，指定逻辑删除的字段
2.建议通过模板生成注释（@author）

感谢作者提供的这么好用的 工具~·

**Comment by xiamaoxuan** [comment]
建议实体上，把索引也加上~~

**Comment by carter-ya** [comment]
目前没有好的方式去做逻辑删除这个功能，你可以参考如下内容
[handling-soft-deletes-with-spring-jpa](https://stackoverflow.com/questions/19323557/handling-soft-deletes-with-spring-jpa)


当前正在重做生成模板，你可以把你想要的特性加入到自己的模板中去.


![image](https://user-images.githubusercontent.com/18641671/125226670-1369b080-e304-11eb-80b5-5bf89c0092eb.png)

**Comment by xiamaoxuan** [comment]
好的
