### ISSUE TITLE
[BUG] 有一个小bug 

### ISSUE THREAD

**Issue by xiamaoxuan** [carter-ya/idea-plugin-jpa-support#121]
勾选掉 序列化 选项 生成的javabean 有问题

**Comment by carter-ya** [comment]
具体的错误示例发一下

**Comment by xiamaoxuan** [comment]
![image](https://user-images.githubusercontent.com/6510160/126439888-6f72b849-4fd8-4f9e-958b-ccc7498decb5.png)
![image](https://user-images.githubusercontent.com/6510160/126439907-9ee63489-b11c-4033-a7b8-09a12b8e7631.png)

**Comment by carter-ya** [comment]
我会在下一版本修复该问题
