### ISSUE TITLE
[BUG] 未对Java关键字进行过滤

### ISSUE THREAD

**Issue by FourLeafTec** [carter-ya/idea-plugin-jpa-support#124]
**Describe the bug （描述这个Bug）**

表里有个字段叫interface...虽然比较奇葩，但是数据库是允许的，甲方的设计的表字段就叫这个，然后生成的类就会出现一个属性名类似下面这种

```
    @Column(name = "interface")
    private String interface;
```

很自然java在这种类里一定会报错

**Expected behavior （期望的行为）**

对java关键字进行过滤，并对属性名添加适当后缀，比如变成interfaceColumn来避免碰到java关键字这样的问题

**idea plugin jpa support version (idea plugin jpa support的版本号）:**
2.0.7

**Comment by carter-ya** [comment]
一个好的提议，下一版本我会加上该特性

**Comment by rxxy** [comment]
想起来一个
如果是数据库关键字的话还应该加`
    @Column(name = "`order`")
    private String order;

**Comment by rxxy** [comment]
```
 @Column(name = "`order`")
private String order;
```

**Comment by rxxy** [comment]
想起来一个
如果是数据库关键字的话还应该加`
