### ISSUE TITLE
[BUG]在生成界面，部分功能项超出显示范围

### ISSUE THREAD

**Issue by suxilee** [carter-ya/idea-plugin-jpa-support#131]
**Describe the bug （描述这个Bug）**
在2560x1600分辨率下，系统推荐放大200%，生成页面超出显示范围。

**Expected behavior （期望的行为）**
加上一个滚动条就好了。

**Screenshots （截图，如果有的话）**
![bug](https://user-images.githubusercontent.com/43755408/132316274-bee998e4-a59b-4b25-b539-7f4cefa77383.png)

**idea version (idea的版本号)**
For example: IntelliJ IDEA 2021.2 (Ultimate Edition)

**idea plugin jpa support version (idea plugin jpa support的版本号）**
For example: 2.0.8-RC1

**OS version (操作系统版本号）**
For example: window11

**Comment by carter-ya** [comment]
问题已收到，安排在下个版本来修复该问题
