### ISSUE TITLE
[BUG]疑似i18n属性文件路径出错

### ISSUE THREAD

**Issue by yulm6** [carter-ya/idea-plugin-jpa-support#148]
**Describe the bug （描述这个Bug）**
生成实体类时抛出异常
**Expected behavior （期望的行为）**
未能生成实体类和仓库类，停滞不前，idea抛出相关异常。

**Screenshots （截图，如果有的话）**
![1638688430(1)](https://user-images.githubusercontent.com/10253074/144737385-40ea3f49-c7d9-4ddf-bae8-dbc0d0e6488b.png)

**idea version (idea的版本号)**
IntelliJ IDEA 2021.2.3 (Community Edition)
Build #IC-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.ifengxue.plugin.jpa-support (2.0.8), idea.plugin.protoeditor (212.5080.8), com.linsage (1.0.6), org.freeone.2ts4j (0.0.10), Spock Framework Enhancements (0.12), org.jetbrains.kotlin (212-1.6.0-release-799-IJ5457.46), com.haulmont.jpab (2021.6.0-212), org.asciidoctor.intellij.asciidoc (0.35.12)
Kotlin: 212-1.6.0-release-799-IJ5457.46

**idea plugin jpa support version (idea plugin jpa support的版本号）**
2.0.8

**OS version (操作系统版本号）**
windows 10

**Comment by carter-ya** [comment]
请更新到2.0.9版本
