### ISSUE TITLE
[BUG] 子类继承公共父类的情况下，生成的Serivce中的save方法中此行代码报错

### ISSUE THREAD

**Issue by ArexdOr** [carter-ya/idea-plugin-jpa-support#213]
**Describe the bug （描述这个Bug）**
当我正常生成JPA实体类的时候，如下页面。生成的service此行代码会错乱
![image](https://user-images.githubusercontent.com/81457763/232365980-4bd96831-e62e-4555-a388-2e8d94f97090.png)

**Expected behavior （期望的行为）**

**Screenshots （截图，如果有的话）**
![image](https://user-images.githubusercontent.com/81457763/232365663-2faf382c-b929-4650-8a91-af838b8a54bf.png)
![image](https://user-images.githubusercontent.com/81457763/232365707-67694812-da83-4605-85ff-6d219a155d5a.png)
![image](https://user-images.githubusercontent.com/81457763/232365734-602a868f-6dfb-433a-8a9c-a9306d7a0671.png)

**idea version (idea的版本号)**
IDEA2023.1

**idea plugin jpa support version (idea plugin jpa support的版本号）**
JDK17

**OS version (操作系统版本号）**
MACOS 12.6.1

**Comment by carter-ya** [comment]
是否可以提供建表语句？
