### ISSUE TITLE
新增编辑模板

### ISSUE THREAD

**Issue by xiejunquan** [carter-ya/idea-plugin-jpa-support#225]
希望能新增或者编辑模板，或者支持R2dbcRepository

**Comment by carter-ya** [comment]
你可以在如下位置自定义模板:
<img width="646" alt="image" src="https://github.com/carter-ya/idea-plugin-jpa-support/assets/18641671/d299484a-7aee-441f-8cea-1b0811c70823">

模板编写可参考 https://github.com/carter-ya/idea-plugin-jpa-support/blob/master/src/main/resources/template/JpaEntity.vm
