### ISSUE TITLE
[BUG] File | Settings | Tools | JPA Support 源码模板(Beta) is empty

### ISSUE THREAD

**Issue by kukuze** [carter-ya/idea-plugin-jpa-support#226]
**Describe the bug （描述这个Bug）**
File | Settings | Tools | JPA Support 源码模板(Beta) is empty。
Mysql8 bigint ->String,

**Expected behavior （期望的行为）**
Support custom db type mapping.Mysql8 bigint ->Long,

**Screenshots （截图，如果有的话）**
![image](https://github.com/carter-ya/idea-plugin-jpa-support/assets/67894866/9ca0a5f8-6869-471e-a3cc-14e109e2263a)

**idea version (idea的版本号)**
For example: IntelliJ IDEA 2019.3.3 (Ultimate Edition)
![image](https://github.com/carter-ya/idea-plugin-jpa-support/assets/67894866/6b77fa7f-adc6-4495-bedb-50dbedbb5d32)

**idea plugin jpa support version (idea plugin jpa support的版本号）**
For example: 1.1.7
![image](https://github.com/carter-ya/idea-plugin-jpa-support/assets/67894866/9e131b16-ac46-49c6-9a34-01811dd46f09)

**OS version (操作系统版本号）**
For example: Mac OS 11.5.1
win11

**Comment by carter-ya** [comment]
<img width="323" alt="image" src="https://github.com/carter-ya/idea-plugin-jpa-support/assets/18641671/cb49842b-8b06-430f-8d21-93f4ffd6d405">

You can click here to customize type mapping.

**Comment by kukuze** [comment]
> bigint and bigint unsigned are two types?

**Comment by carter-ya** [comment]
> ![image](https://private-user-images.githubusercontent.com/67894866/330714806-9b7462a5-38e8-4f59-ae24-1e8e93face8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzE4NjUsIm5iZiI6MTcxNjI3MTU2NSwicGF0aCI6Ii82Nzg5NDg2Ni8zMzA3MTQ4MDYtOWI3NDYyYTUtMzhlOC00ZjU5LWFlMjQtMWU4ZTkzZmFjZThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA2MDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNjM1YjdmZjgxYjZhMWQyNDQzZjhhOGI5M2Q5YWY0OWJiNzc1YmIwMWViYWI2OGU5YzkzYmJjNWIxNDNhZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNPMU3-uH_P0BESgFjgqbLYX3Eq0nvppFGZo1WqA1Yo) ![image](https://private-user-images.githubusercontent.com/67894866/330714989-44a7e088-ac90-42a3-b519-96be31c29ba8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNzE4NjUsIm5iZiI6MTcxNjI3MTU2NSwicGF0aCI6Ii82Nzg5NDg2Ni8zMzA3MTQ5ODktNDRhN2UwODgtYWM5MC00MmEzLWI1MTktOTZiZTMxYzI5YmE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDA2MDYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMDA1YWNjOTUyNTUwODk1NGY3NTZkYjgyYTQzN2NiOTYwMTRmZjE4NDljMGU3ZDQxYTMyYzZjMTczNmNlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ORgVJ12im9gr3hOdtNLiEpyXoJaSc1CCFTaIyhUEcIY) bigint and bigint unsigned are two types?

yes
