### ISSUE TITLE
mysql字段映射问题

### ISSUE THREAD

**Issue by yakamy** [carter-ya/idea-plugin-jpa-support#47]
如果数据库字段类型为 tinyint
java实体中映射为Integer 需要增加 注解 
@Column(columnDefinition = "TINYINT")
@Type(type = "org.hibernate.type.IntegerType")
否则会报错。。。

**Comment by carter-ya** [comment]
请问报什么错呢，我这面使用是没遇到过

**Comment by yakamy** [comment]
开启验证（spring.jpa.hibernate.ddl-auto=validate）的时候报这个错，加上那两个注解就好了
Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: missing column [call_type] in table [product]

**Comment by Machsis** [comment]
数据库mediumblob类型 被转换成String了, 是不支持识别Blob类型吗

**Comment by carter-ya** [comment]
> 数据库mediumblob类型 被转换成String了, 是不支持识别Blob类型吗

[idea-plugin-jpa-support.zip](https://github.com/carter-ya/idea-plugin-jpa-support/files/4484845/idea-plugin-jpa-support.zip)

请下载这个版本来解决你的问题
