### ISSUE TITLE
MS SQL driver 

### ISSUE THREAD

**Issue by DamirIdiatulin** [carter-ya/idea-plugin-jpa-support#50]
Hello
how i can use your plugin for MS SQL SERVER DB ?
can you add driver to support connection with MS SQL DB

**Comment by carter-ya** [comment]
Sorry, I don’t know how to use MS SQL Server, but you can inherit [AbstractDriverAdapter](https://github.com/carter-ya/idea-plugin-jpa-support/blob/e10a8c3cb028a134ad24072f3faa9d4febbe9569/src/com/ifengxue/plugin/adapter/AbstractDriverAdapter.java#L6) and implement related methods, and register the driver.

**Comment by carter-ya** [comment]
If you use idea ultimate, you can support all types of databases

**Comment by carter-ya** [comment]
@DamirIdiatulin Please download the latest version, already supports all known database types.
