### ISSUE TITLE
Entity变量大小写问题

### ISSUE THREAD

**Issue by Tomosawa** [carter-ya/idea-plugin-jpa-support#51]
您好，挺喜欢这个工具的，很好用，有几个问题想反馈一下。
利用工具生成Entity之后，例如数据库中列命名为UserName，那么生成的Entity中是：
    @Column(name = "UserName")
    private String UserName;
首字母是大写的，导致在写Repository的 findByUserName(String userName);的时候，直接报错，无法找到。把首字母改小写才行，但是发现其他的也全部都是大写的，全部都改一遍岂不是很麻烦？？？

**Comment by carter-ya** [comment]
[idea-plugin-jpa-support.zip](https://github.com/carter-ya/idea-plugin-jpa-support/files/4378713/idea-plugin-jpa-support.zip)

这个是修复后的版本，你安装下试试，是否能够解决你的问题

**Comment by Tomosawa** [comment]
> [idea-plugin-jpa-support.zip](https://github.com/carter-ya/idea-plugin-jpa-support/files/4378713/idea-plugin-jpa-support.zip)
> 
> 这个是修复后的版本，你安装下试试，是否能够解决你的问题

问题已经解决了！非常感谢！！！希望这个小插件能越来越好~
