### ISSUE TITLE
[BUG]Mysql字段映射问题

### ISSUE THREAD

**Issue by Machsis** [carter-ya/idea-plugin-jpa-support#55]
`    /**
     * 文件内容
     */
    @Column(name = "CONTENT")
    private String CONTENT;
`

默认的java字段不应该是小写开头,驼峰命名吗, 在只有一个单词的时候会变成大写, 有没有跟我一样的情况
我的mysql是5.7

**Comment by carter-ya** [comment]
这确实是一个bug，你下载下这个版本看看是否能解决 [去下载](https://github.com/carter-ya/idea-plugin-jpa-support/issues/51#issuecomment-603609038)

**Comment by Machsis** [comment]
好嘞, 插件很不错, 谢谢分享
