### ISSUE TITLE
Choose schema for postgres

### ISSUE THREAD

**Issue by akorob** [carter-ya/idea-plugin-jpa-support#58]
Currently, the user can generate entities only from schema public in Postgres DB. It's good idea to enable generation from other schemes.

**Comment by carter-ya** [comment]
If you use idea ultimate, you can support all types of databases

**Comment by samirissa00** [comment]
Hi , this feature is very important !! PostgreSQL use schema and databases structures on production environment it is normal change the default names !! Thanks !

**Comment by carter-ya** [comment]
@samirissa00  

Do you use idea ulitimate? If so, the plugin can generate code directly using the database plugin.

**Comment by samirissa00** [comment]
Hi , no i`m a free lancer i use the CE ( community ) ,  i think that this plugin is to use in CE or is it to Ultimate ?

**Comment by carter-ya** [comment]
This plugin supports idea CE and idea ultimate. If you use idea ultimate, my plugin will provide richer functions, such as supporting more database types.
But I'm fixing the problem you just said. Please wait a moment.

**Comment by carter-ya** [comment]
@samirissa00 
Please download the EAP version first. If you have any other questions, please feedback in time.
[Jpa Support-2.0.4-EAP.zip](https://github.com/carter-ya/idea-plugin-jpa-support/files/5137187/Jpa.Support-2.0.4-EAP.zip)
