### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by kalkrishnan** [carter-ya/idea-plugin-jpa-support#60]
Can I get the build instructions for this? I wanted to enhance this but am unable to build it

**Comment by carter-ya** [comment]
Current project use `Gradle`, you can read dev document at [Building Plugins with Gradle
](https://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system.html),
You also can push a `Pull Request`.

**Comment by kalkrishnan** [comment]
Not sure a pull request would work as I had to remove a lot of the exception logging code because of mandarin characters which my IDE didnt work. I added compatibility to intellij 2020 and gradle 7+, plus I wanted to add support for jsonb columns with postgres which I did. I can send a PR if you want. Ill probably have to fork the repo for that since I dont have permission to push a branch to this repo.
