### ISSUE TITLE
想修改下模版

### ISSUE THREAD

**Issue by rxxy** [carter-ya/idea-plugin-jpa-support#61]
想在每个实体上加一些注解，类似这样的
@SQLDelete(sql = "update sys_user set deleted = 1 where id = ?")
@Where(clause = "deleted = 0")
@EntityListeners({AuditingLogListener.class})

repository上的话也需要继承下自己的repository父类。

可以提供修改模版的地方吗，或者加一些自定义的选项

**Comment by carter-ya** [comment]
嗯，接下来会允许自定义模板

**Comment by rxxy** [comment]
那太好了，感谢

**Comment by carter-ya** [comment]
新版本已经支持修改模板了
