### ISSUE TITLE
[BUG]时间戳默认值怎么办?

### ISSUE THREAD

**Issue by kingwrcy** [carter-ya/idea-plugin-jpa-support#62]
`created_time      timestamp(3)   default CURRENT_TIMESTAMP(3) not null,

update_time       timestamp(3)   default CURRENT_TIMESTAMP(3) not null on update CURRENT_TIMESTAMP(3)`

数据库有默认值,repository.save的时候会传个null进去,导致保存失败了
我看其他的字段有默认值是通过在定义变量的时候就给了默认值,时间戳这个怎么处理呢?

现在我是手动在entity类顶上加上
`@DynamicInsert

@DynamicUpdate`

很麻烦,重新生成一次就覆盖了.
要么支持加上这2个注解如何?

另外 UI界面有个错字
![0e6250ff55b10f96](https://user-images.githubusercontent.com/1247324/87516762-7d7b5580-c6b0-11ea-831d-09d4301144c9.png)

**Comment by carter-ya** [comment]
下一版本允许勾选时间戳类型字段添加默认值

**Comment by liaozan** [comment]
提个小建议，如果是tinyint(1)字段类型可以默认是boolean

**Comment by carter-ya** [comment]
新版本已经支持是否生成默认值了
