### ISSUE TITLE
check the box USE JAVA 8 DATA TYPE but fail to generate correct class

### ISSUE THREAD

**Issue by sjpf233** [carter-ya/idea-plugin-jpa-support#86]
**Describe the bug （描述这个Bug）**
I have checked the box USE JAVA 8 DATA TYPE but failed to generate LocaleDateTime for the corresponding mysql type datetime. And in the previous version, it can be done it correctly

**Expected behavior （期望的行为）**
generate LocateDateTime for datetime when check USE JAVA 8 DATA TYPE

**Screenshots （截图，如果有的话）**
![image](https://user-images.githubusercontent.com/15214135/106723551-30f26a00-6642-11eb-98a3-d2bdb4b2f401.png)
![image](https://user-images.githubusercontent.com/15214135/106725210-128d6e00-6644-11eb-857c-727239ac5e43.png)

**idea version (idea的版本号):**
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7

**idea plugin jpa support version (idea plugin jpa support的版本号）:**
2.0.6EAP

**Comment by carter-ya** [comment]
You can fix it this way first
![image](https://user-images.githubusercontent.com/18641671/106736122-03142200-6650-11eb-9295-9c75df6a4f3c.png)

**Comment by sjpf233** [comment]
After I config this type mapping, it seems that all type mapping failed and fell back to java.lang.String, and I check the throw exception if there is no mapping, the plugin would throw a exception
![image](https://user-images.githubusercontent.com/15214135/106744723-1678ba80-665b-11eb-9167-00ffc667e00a.png)
![image](https://user-images.githubusercontent.com/15214135/106744389-a8cc8e80-665a-11eb-8f4b-95ff614efea3.png)

**Comment by sjpf233** [comment]
I restart my Idea, and it works well now, thank you very much.

**Comment by carter-ya** [comment]
I'm sorry you encountered such a problem, please try to uninstall and install again.
![image](https://user-images.githubusercontent.com/18641671/106747906-7709f680-665f-11eb-9d68-247eef13f69b.png)

and try to delete this file
![image](https://user-images.githubusercontent.com/18641671/106748201-d5cf7000-665f-11eb-8cee-1c54b3db7e1a.png)

**Comment by sjpf233** [comment]
Thank you very much, I restart my Idea, and it works well now.
