### ISSUE TITLE
[BUG]Entity的Table注解中无schema和catalog信息

### ISSUE THREAD

**Issue by rainmanhhh** [carter-ya/idea-plugin-jpa-support#92]
生成出来类似于这样
```
@Entity
@Table(name = "user")
```
连接地址中不带schema的话（比如jdbc:mysql://127.0.0.1:3306), 运行时访问数据库会报java.sql.SQLException: No database selected（mysql）
但问题是程序要访问多个schema，就必须在表上指定，而不能在jdbc连接上指定

对于不同的数据库，应该是有schema则生成schema（比如mysql），有catalog则生成catalog（比如oracle），都没有才留空

**Comment by carter-ya** [comment]
这是个新特性，下一版本中会加入

**Comment by rainmanhhh** [comment]
> 这是个新特性，下一版本中会加入

下一版能否直接在数据库上右键生成？现在必须要把一堆表都选中了再右键生成，问题是弹出来的对话框里不是本来就可以筛选表么（还可以用正则表达式筛选）

**Comment by carter-ya** [comment]
> > 这是个新特性，下一版本中会加入
> 
> 下一版能否直接在数据库上右键生成？现在必须要把一堆表都选中了再右键生成，问题是弹出来的对话框里不是本来就可以筛选表么（还可以用正则表达式筛选）

一个好的改进，下一版本中支持这种复合模式

**Comment by carter-ya** [comment]
https://plugins.jetbrains.com/plugin/10707-jpa-support/versions/stable/113718

最新版已发布
