### ISSUE TITLE
No table comments are generated (Mysql)

### ISSUE THREAD

**Issue by erengong** [carter-ya/idea-plugin-jpa-support#96]
The new version of swagger annotation does not generate table annotations.

**Comment by carter-ya** [comment]
Maybe you should reset your tempalte.

![image](https://user-images.githubusercontent.com/18641671/112277757-08d7cc80-8cbd-11eb-8ebf-8e2f2c6ccb0a.png)

**Comment by erengong** [comment]
The problem seems to still exist, the table comment cannot be generated.
![image](https://user-images.githubusercontent.com/30641365/112280029-88669b00-8cbf-11eb-80ee-1368ba76c46c.png)
![image](https://user-images.githubusercontent.com/30641365/112280111-9e745b80-8cbf-11eb-9f1f-21189bd241da.png)
![image](https://user-images.githubusercontent.com/30641365/112280146-a8965a00-8cbf-11eb-944f-96c0851e48ad.png)
![image](https://user-images.githubusercontent.com/30641365/112280269-cbc10980-8cbf-11eb-8c00-b96b9a0b4693.png)

**Comment by carter-ya** [comment]
What version of mysql driver are you using?

You can try use this version [mysql-connector-java-8.0.23](https://mvnrepository.com/artifact/mysql/mysql-connector-java/8.0.23)
![image](https://user-images.githubusercontent.com/18641671/112282644-3ffcac80-8cc2-11eb-83ac-4f99d095bbdf.png)

**Comment by erengong** [comment]
Previously I used 8.0.22, this time I used 8.0.23, the same effect.
![image](https://user-images.githubusercontent.com/30641365/112283536-358ee280-8cc3-11eb-91cd-5fbf7a5a1ae9.png)

**Comment by carter-ya** [comment]
Can you provide the table schema and mysql database version?

**Comment by erengong** [comment]
mysql database version: `5.6.27-log`
table schema:
```sql
CREATE TABLE `t_auth_role` (
    `f_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `f_platform` tinyint(4) NOT NULL COMMENT '所属平台(1-平台管理/2-代理商管理/3-企业管理)',
    `f_corp_id` bigint(20) NOT NULL COMMENT '企业ID',
    `f_name` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '权限名称',
    `f_super_admin` tinyint(1) NOT NULL DEFAULT '0' COMMENT '超级管理员',
    `f_remark` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '备注',
    `f_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '已删除(true-是/false-否)',
    `f_operator` bigint(20) NOT NULL DEFAULT '0' COMMENT '操作者ID',
    `f_create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `f_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (`f_id`),
    KEY `idx_corp_id` (`f_corp_id`)
) ENGINE = InnoDB AUTO_INCREMENT = 685 DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '权限管理 - 角色表'
```

**Comment by erengong** [comment]
I don’t think it’s a problem with the table schema, because all my tables have this problem, since the new version of the idea-plugin.
![image](https://user-images.githubusercontent.com/30641365/112285065-de8a0d00-8cc4-11eb-8830-7c6da86f75e5.png)

**Comment by carter-ya** [comment]
Maybe you should refer to this answer: [Retrieve mysql table comment using DatabaseMetaData](https://stackoverflow.com/a/14146809/7022419)

**Comment by carter-ya** [comment]
![image](https://user-images.githubusercontent.com/18641671/112287930-d1bae880-8cc7-11eb-95db-cd181181a57c.png)
![image](https://user-images.githubusercontent.com/18641671/112287976-dda6aa80-8cc7-11eb-893a-d809b66b9a8c.png)

**Comment by erengong** [comment]
perfect! Just add this parameter: `useInformationSchema=true`.Thank you very much.
![image](https://user-images.githubusercontent.com/30641365/112288634-80f7bf80-8cc8-11eb-8ef0-0faa669fa9a7.png)
