### ISSUE TITLE
blank space

### ISSUE THREAD

**Issue by zwxx960** [carter-ya/idea-plugin-jpa-support#97]
if column name contains blank spaces, the field name generated will contain those as well - so compiling error.

**Comment by carter-ya** [comment]
You can try this version to fix the problem
[JPA Support.zip](https://github.com/carter-ya/idea-plugin-jpa-support/files/6197984/JPA.Support.zip)

**Comment by zwxx960** [comment]
please release a new version again(・∀・).

**Comment by carter-ya** [comment]
You can download from [JetBrains](https://plugins.jetbrains.com/plugin/10707-jpa-support/versions/Unstable/114871)
